package app

var MajorCities = []string{
	"New York, NY USA",
	"Los Angeles, CA USA",
	"Chicago, IL USA",
	"Houston, TX USA",
	"Phoenix, AZ USA",
	"Philadelphia, PA USA",
	"San Antonio, TX USA",
	"San Diego, CA USA",
	"Dallas, TX USA",
	"San Jose, CA USA",
	"Austin, TX USA",
	"Jacksonville, FL USA",
	"Fort Worth, TX USA",
	"Columbus, OH USA",
	"Charlotte, NC USA",
	"Indianapolis, IN USA",
	"San Francisco, CA USA",
	"Seattle, WA USA",
	"Denver, CO USA",
	"Washington, D.C. USA",
	"Boston, MA USA",
	"El Paso, TX USA",
	"Nashville, TN USA",
	"Detroit, MI USA",
	"Oklahoma City, OK USA",
	"Portland, OR USA",
	"Las Vegas, NV USA",
	"Memphis, TN USA",
	"Louisville, KY USA",
	"Baltimore, MD USA",
	"Milwaukee, WI USA",
	"Albuquerque, NM USA",
	"Tucson, AZ USA",
	"Fresno, CA USA",
	"Mesa, AZ USA",
	"Sacramento, CA USA",
	"Atlanta, GA USA",
	"Kansas City, MO USA",
	"Colorado Springs, CO USA",
	"Miami, FL USA",
	"Raleigh, NC USA",
	"Toronto, Canada",
	"Sydney, Australia",
	"Melbourne, Australia",
	"Brisbane, Australia",
	"Perth, Australia",
	"Auckland, New Zealand",
	"Wellington, New Zealand",
	"London, UK",
	"Birmingham, UK",
	"Manchester, UK",
	"Liverpool, UK",
	"Edinburgh, UK",
	"Dublin, Ireland",
	"Singapore, Singapore",
	"Cape Town, South Africa",
	"Johannesburg, South Africa",
	"Durban, South Africa",
	"Omaha, NE USA"}
